#!/bin/bash
# Builds Burndown.app from the Swift sources, no Xcode project required.
set -euo pipefail
cd "$(dirname "$0")"

APP="Burndown.app"
BIN="Burndown"
MACOS_DIR="$APP/Contents/MacOS"

# Build IN PLACE (never rm the bundle): keeps the bundle path + signature identity stable so the
# macOS Accessibility (TCC) grant survives rebuilds, which is what makes zero-lag tracking durable.
echo "→ Preparing build (in place)"
mkdir -p "$MACOS_DIR" "$APP/Contents/Resources"

echo "→ Compiling Swift sources"
# Build for THIS machine. Hardcoding arm64 here meant an Intel Mac compiled, signed and printed
# "Built" while producing a binary it could not run. release.sh is the one that builds both
# slices and lipos them into the universal bundle that ships.
# Recursive on purpose: a flat Sources/*.swift silently skips files the day Sources/ grows a
# subdirectory, and the failure mode is link errors that read like something else entirely.
swiftc -O \
  -target "$(uname -m)-apple-macos13.0" \
  -framework AppKit -framework SwiftUI -framework Combine -framework Charts -framework UserNotifications -framework ServiceManagement \
  -o "$MACOS_DIR/$BIN" \
  $(find Sources -name '*.swift' | sort)

echo "→ Writing Info.plist"
# Single source of truth for the version: kAppVersion in Sources/Settings.swift.
VERSION="$(sed -n 's/^let kAppVersion = "\([^"]*\)".*/\1/p' Sources/Settings.swift)"
# NO fallback. This used to default to 1.0, which is worse than any failure it was covering: 1.0
# is from the abandoned 1.x scheme AND it sorts above every real version, so a build stamped with
# it would report a version that never existed and could never be superseded by a 0.9.x release.
# The updater would go quiet forever. If the version cannot be read, that is a broken build, and a
# broken build should stop rather than invent a number.
[ -n "$VERSION" ] || { echo "ABORT: could not read kAppVersion from Sources/Settings.swift"; exit 1; }
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>Burndown</string>
    <key>CFBundleDisplayName</key>     <string>Burndown</string>
    <key>CFBundleIdentifier</key>      <string>com.maz.burndown</string>
    <key>CFBundleVersion</key>         <string>$VERSION</string>
    <key>CFBundleShortVersionString</key> <string>$VERSION</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>Burndown</string>
    <key>CFBundleIconFile</key>        <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>  <string>13.0</string>
    <key>LSUIElement</key>             <true/>
    <key>NSPrincipalClass</key>        <string>NSApplication</string>
    <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

# App icon: build the .icns from the source PNG if it's not already in the bundle (the in-place
# build keeps it across rebuilds; delete it to force a refresh after editing Icon/mkicon.swift).
if [ ! -f "$APP/Contents/Resources/AppIcon.icns" ] && [ -f Icon/AppIcon-1024.png ]; then
    echo "→ Building app icon"
    ICONSET="$(mktemp -d)/AppIcon.iconset"; mkdir -p "$ICONSET"
    for s in 16 32 128 256 512; do
        sips -z $s $s Icon/AppIcon-1024.png --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
        d=$((s * 2)); sips -z $d $d Icon/AppIcon-1024.png --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
    done
    cp Icon/AppIcon-1024.png "$ICONSET/icon_512x512@2x.png"
    iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns" 2>/dev/null || echo "  (icon build skipped)"
fi

# Bundle Burndown's own original alert chimes (Sounds/, generated by Sounds/make_sounds.py).
# UNNotificationSound resolves them from the app's Resources. No Apple audio ships in the app;
# any Apple .aiff a previous build copied in is removed here.
rm -f "$APP/Contents/Resources"/{Glass,Ping,Funk,Submarine,Hero,Pop}.aiff
cp Sounds/*.wav "$APP/Contents/Resources/" 2>/dev/null || true

# Bundle the docs the About window opens (What's new / Privacy). Always refresh.
cp docs/RELEASE_NOTES.md docs/PRIVACY.md "$APP/Contents/Resources/" 2>/dev/null || true

echo "→ Ad-hoc code signing"
# Cloud-sync folders and some tools attach extended attributes (resource forks, Finder info)
# to files. codesign rejects those ("resource fork ... not allowed"), and a bundle signed with
# stale or partial resources is killed at launch with "Code Signature Invalid". Strip xattrs
# first so the signature is always clean and valid.
xattr -cr "$APP" 2>/dev/null || true
codesign --force --sign - --identifier com.maz.burndown "$APP" 2>/dev/null || echo "  (codesign skipped)"
codesign -v "$APP" 2>/dev/null && echo "  signature valid" || echo "  WARNING: signature did not verify"

# If the launch-at-login agent is installed, restart it so it picks up the freshly-built binary.
# Re-signing (ad-hoc) changes the code hash, and launchd caches a launch code-requirement (LWCR)
# tied to the OLD hash - a plain `kickstart -k` then fails with OS_REASON_CODESIGNING ("spawn
# failed"). Bootout + bootstrap re-registers the job so it re-derives the requirement.
UID_="$(id -u)"; PLIST="$HOME/Library/LaunchAgents/com.maz.burndown.plist"
if launchctl print "gui/$UID_/com.maz.burndown" >/dev/null 2>&1; then
    launchctl bootout "gui/$UID_/com.maz.burndown" 2>/dev/null || true
    sleep 2   # bootout is async; bootstrap fails if the old job is still registered
    if launchctl bootstrap "gui/$UID_" "$PLIST" 2>/dev/null; then
        launchctl kickstart "gui/$UID_/com.maz.burndown" 2>/dev/null && echo "→ Re-registered + restarted login agent"
    else
        echo "  WARNING: could not re-register the login agent (run: launchctl bootstrap gui/$UID_ $PLIST)"
    fi
fi

echo "✓ Built $APP"
